SAILAPIGuide: led.h File Reference
led.h File Reference
Detailed Description
led driver
============================================================================
The LED header file should be included in an application as follows:
#include <led.h>
Operation
An LED driver simplifies using a LED (may be GPIO or PWM controlled) available on board and supports following operations -
1. To Turn ON/OFF
2. Blink with requested delay, stop when requested
3. Vary brightness(can only be done to a PWM controlled LED)
4. Toggle
There are also APIs to open and close an LED handle and also one to get current state of a LED. User can request to set a LED into particular state while opening itself i.e. to start blink as part of LED_open() call.
Information about LEDs and their instances will be available in board specific example files.
A LED_config array should be defined by the application. This LED_config array should contain pointers to a defined LED_HWAttrs and allocated array of LED_Object structure. LED_init() must be called before using LED_open().
Any GPIO pins must be configured and then initialized by using GPIO_Init(). Similarly, any PWM pins must be configured and then initialized by using PWM_init().
The APIs in this driver serve as an interface to a DPL(Driver Porting Layer) The specific implementations are responsible for creating all the RTOS specific primitives to allow for thread-safe operation.
This driver has no dynamic memory allocation.
Defining LED_Config, LED_Object and LED_HWAttrs
To use SAIL LED driver, an application has to indicate how many LEDs it wants to operate, of what type(PWM or GPIO controlled) and which GPIO to index for controlling an LED.
Each structure must be defined by the application. The following example is for an MSP432P401R platform in which four LEDs are available on board. The following declarations are placed in "MSP_EXP432P401R.h" and "MSP_EXP432P401R.c" respectively. How the gpioIndices are defined are detailed in the next section.
"MSP_EXP432P401R.h"
typedef enum MSP_EXP432P401R_LEDName {
    MSP_EXP432P401R_GPIO_LED1 = 0,
    MSP_EXP432P401R_GPIO_RGBLED,
    MSP_EXP432P401R_PWM_GREENLED,
    MSP_EXP432P401R_PWM_BLUELED,
    MSP_EXP432P401R_LEDCOUNT
} MSP_EXP432P401R_LEDName;
"MSP_EXP432P401R.c"
 #include <led.h>
#define MSP_EXP432P401R_NA_GPIO_PWMLED    0xFFFF
 LED_Object LED_object[MSP_EXP432P401R_LEDCOUNT];
 const LED_HWAttrs LED_hwAttrs[MSP_EXP432P401R_LEDCOUNT] = {
         {
             .gpioIndex = MSP_EXP432P401R_LED1,
         },
         {
             .gpioIndex = MSP_EXP432P401R_LED_RED,
         },
         {
             .gpioIndex = MSP_EXP432P401R_NA_GPIO_PWMLED,
         },
         {
             .gpioIndex = MSP_EXP432P401R_NA_GPIO_PWMLED,
         }
 };
 const LED_Config LED_config[] = {
     {
         .object =  &LED_object[0],
         .hwAttrs = &LED_hwAttrs[0],
     },
     {
         .object =  &LED_object[1],
         .hwAttrs = &LED_hwAttrs[1],
     },
     {
         .object =  &LED_object[2],
         .hwAttrs = &LED_hwAttrs[2],
     },
     {
         .object =  &LED_object[3],
         .hwAttrs = &LED_hwAttrs[3],
     },
     {NULL, NULL},
 };
LED_config is implemented in the application with each entry being an instance of a implementation. Last instance is marked by NULL terminated LED_config structure inside config array.
Setting up GPIO configurations
The following code snippet shows how a GPIO pin controlling an LED is configured. The following definitions are in "MSP_EXP432P401R.h" and "MSP_EXP432P401R.c" respectively. This example uses GPIO pins 1.0 and 2.0 which control LED1 and RED LED on launchpad respectively.
"MSP_EXP432P401R.h"
typedef enum MSP_EXP432P401R_GPIOName {
    MSP_EXP432P401R_S1 = 0,
    MSP_EXP432P401R_S2,
    MSP_EXP432P401R_LED1,
    MSP_EXP432P401R_LED_RED,
    MSP_EXP432P401R_GPIOCOUNT
} MSP_EXP432P401R_GPIOName;
"MSP_EXP432P401R.c"
#include <gpio.h>
GPIO_PinConfig gpioPinConfigs[] = {
    GPIOMSP432_P1_1 | GPIO_CFG_IN_PU | GPIO_CFG_IN_INT_RISING,
    GPIOMSP432_P1_4 | GPIO_CFG_IN_PU | GPIO_CFG_IN_INT_RISING,
    GPIOMSP432_P1_0 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW,
    GPIOMSP432_P2_0 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW,
}
Opening a PWM_Handle Handle
The PWM module instance has to be created for servicing requests to set light intensity. The pwm parameters like period, duty and polarity can be set by application before opening a pwm handle and embedding inside LED params structure before opening an handle for PWM controlled LED.
To let an LED controlled by PWM, GPIO settings for that particular pin has to be commented inside gpioPinConfigs[] structure. It shall also be known beforehand which PWM timer can be muxed to that pin. In "MSP_EXP432P401R.c" file
GPIO_PinConfig gpioPinConfigs[] = {
  GPIOMSP432_P1_1 | GPIO_CFG_IN_PU | GPIO_CFG_IN_INT_RISING,
  GPIOMSP432_P1_4 | GPIO_CFG_IN_PU | GPIO_CFG_IN_INT_RISING,
  GPIOMSP432_P1_0 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW,
  //GPIOMSP432_P2_0 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW,
  //GPIOMSP432_P2_1 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW,
  //GPIOMSP432_P2_2 | GPIO_CFG_OUT_STD | GPIO_CFG_OUT_STR_HIGH | GPIO_CFG_OUT_LOW
};
In application code, testled.c
#include <ti/drivers/PWM.h>
PWM_Handle pwmHandle = NULL;
PWM_Params params;
PWM_Params_init(&params);
params.period = pwmPeriod;
pwmHandle = PWM_open(Board_PWM0, &params);
Opening a LED with default parameters
#include <LED.h>
LED_Handle LEDHandle;
LED_Params_init(&ledParams);
ledHandle = LED_open(Board_LED0, &ledParams);
#include <stdint.h>
#include <stdbool.h>
#include <pthread.h>
#include <time.h>
#include <ti/drivers/GPIO.h>
#include <ti/drivers/PWM.h>
Data Structures
struct LED_Config
LED configuration.
struct LED_HWAttrs
Hardware specific settings for a LED module.
struct LED_Object
LED Object structure.
struct LED_Params
LED Parameters.
Macros
#define LED_BRIGHTNESS_MAX 100U /* Max brightness in % is 100%*/
#define LED_BRIGHTNESS_MIN 0U /* Max brightness in % is 0%*/
#define LED_ON 1U
#define LED_OFF 0U
Typedefs
typedef enum LED_Type LED_Type
LED types based on control source.
typedef enum LED_State LED_State
LED State.
typedef struct LED_Config LED_Config
LED configuration.
typedef struct LED_Config * LED_Handle
A handle that is returned from a LED_open() call.
typedef struct LED_HWAttrs LED_HWAttrs
Hardware specific settings for a LED module.
typedef struct LED_Object LED_Object
LED Object structure.
typedef struct LED_Params LED_Params
LED Parameters.
Enumerations
enum LED_Type { LED_GPIO_CONTROLLED = 0, LED_PWM_CONTROLLED }
LED types based on control source.
enum LED_State { LED_STATE_OFF = 0, LED_STATE_ON, LED_STATE_BLINKING }
LED State.
Functions
void LED_close (LED_Handle ledHandle)
Function to close a LED specified by the LED handle.
LED_State LED_getState (LED_Handle ledHandle)
Function to get LED state.
void LED_init ()
Function to initialize LED driver.
LED_Handle LED_open (unsigned int ledIndex, LED_Params *params)
Function to open an instance of LED.
void LED_initParams (LED_Params *params)
Function to initialize a LED_Params struct to its defaults.
bool LED_setBrightnessLevel (LED_Handle ledHandle, uint16_t level)
Function to set brightness level of a LED.
void LED_setOff (LED_Handle ledHandle)
Function to turn off a LED.
bool LED_setOn (LED_Handle ledHandle, uint16_t brightness)
Function to turn on a LED.
void LED_startBlinking (LED_Handle ledHandle, uint16_t blinkPeriod)
Function to start a LED blinking.
void LED_stopBlinking (LED_Handle ledHandle)
Function to stop a LED blinking.
void LED_toggle (LED_Handle ledHandle)
Function to toggle a LED.
Macro Definition Documentation
LED_BRIGHTNESS_MAX
#define LED_BRIGHTNESS_MAX 100U /* Max brightness in % is 100%*/
Referenced by LED_setBrightnessLevel().
LED_BRIGHTNESS_MIN
#define LED_BRIGHTNESS_MIN 0U /* Max brightness in % is 0%*/
Referenced by LED_setOff().
LED_ON
#define LED_ON 1U
Referenced by LED_setOn().
LED_OFF
#define LED_OFF 0U
Referenced by LED_setOff().
Typedef Documentation
LED_Type
typedef enum LED_Type LED_Type
LED types based on control source.
A LED can be controlled by GPIO or PWM. Only a PWM controlled LED can be operated to show brightness variation.
LED_State
typedef enum LED_State LED_State
LED State.
A LED can be in OFF, ON or BLINKING state
State of particular LED may be tied with a warning/alert in system which a thread/task may want to know.
LED_Config
typedef struct LED_Config LED_Config
LED configuration.
The LED_Config structure contains a set of pointers used to characterize the LED driver implementation.
This structure needs to be defined and provided by the application and will be NULL terminated.
LED_Handle
typedef struct LED_Config* LED_Handle
A handle that is returned from a LED_open() call.
LED_HWAttrs
typedef struct LED_HWAttrs LED_HWAttrs
Hardware specific settings for a LED module.
This structure should be defined and provided by the application. The gpioIndex should be defined in accordance of the GPIO driver. The pin must be configured as GPIO_CFG_INPUT and GPIO_CFG_IN_INT_FALLING.
LED_Object
typedef struct LED_Object LED_Object
LED Object structure.
The application must not access any member variables of this structure!
LED_Params
typedef struct LED_Params LED_Params
LED Parameters.
LED parameters are used with the LED_open() call. Default values for these parameters are set using LED_Params_init(). It contains brightness field which will be used to control brightness of a LED and also blink period if user wants to set LED in blinking mode.
See also
LED_Params_init()
Enumeration Type Documentation
LED_Type
enum LED_Type
LED types based on control source.
A LED can be controlled by GPIO or PWM. Only a PWM controlled LED can be operated to show brightness variation.
Enumerator
LED_GPIO_CONTROLLED
LED_PWM_CONTROLLED
LED_State
enum LED_State
LED State.
A LED can be in OFF, ON or BLINKING state
State of particular LED may be tied with a warning/alert in system which a thread/task may want to know.
Enumerator
LED_STATE_OFF
LED_STATE_ON
LED_STATE_BLINKING
Function Documentation
LED_close()
void LED_close (LED_Handle ledHandle)
Function to close a LED specified by the LED handle.
The LED close API to close the LED instance specified by ledHandle.
This call will destruct associated timer if running and turn off LED, can be hooked up with Power Down sequence in system.
Precondition
LED_open() had to be called first.
Parameters
ledHandle A LED_Handle returned from LED_open()
References LED_setOff(), LED_stopBlinking(), LED_Config::object, and LED_Object::timer.
LED_getState()
LED_State LED_getState (LED_Handle ledHandle)
Function to get LED state.
This function may be useful in scenarios if a LED state(ON/OFF/BLINKING) is tied with some system warning/alerts
Parameters
ledHandle A LED_Handle returned from LED_open()
Returns
The LED State
References LED_Config::object, and LED_Object::state.
LED_init()
void LED_init ()
Function to initialize LED driver.
This function will initialize the LED driver.
LED_open()
LED_Handle LED_open (unsigned int ledIndex, LED_Params * params)
Function to open an instance of LED.
Function to initialize a given LED specified by the particular index value.LED parameters must be setup and PWM handle opened(only for PWM controlled LED type) before this call.
User may request to set LED into particular state, for ex: open an handle and start blinking that LED or just turn in ON or OFF
Precondition
LED_init() has to be called first
Parameters
ledIndex Logical led number indexed into the LED_config table
*params A pointer to LED_Params structure. If NULL, it will use default values.
Returns
A LED_Handle on success, or a NULL on failure.
See also
LED_init()
LED_Params_init()
LED_close()
LED_initParams()
void LED_initParams (LED_Params * params)
Function to initialize a LED_Params struct to its defaults.
Parameters
params A pointer to LED_Params structure for initialization.
Default values are: ledType = LED_GPIO_CONTROLLED brightness = LED_BRIGHTNESS_MAX
References LED_defaultParams.
LED_setBrightnessLevel()
bool LED_setBrightnessLevel (LED_Handle ledHandle, uint16_t level)
Function to set brightness level of a LED.
Ignores brightness settings if LED is not PWM controlled
Parameters
ledHandle A LED handle
level Brightness level in terms of percentage 0-100 %
Returns
true on success or false upon failure.
References LED_Object::brightness, LED_BRIGHTNESS_MAX, LED_GPIO_CONTROLLED, LED_PWM_CONTROLLED, LED_Object::ledType, LED_Config::object, LED_Object::pwmHandle, and LED_Object::pwmPeriod.
Referenced by LED_setOff(), and LED_setOn().
LED_setOff()
void LED_setOff (LED_Handle ledHandle)
Function to turn off a LED.
Parameters
ledHandle A LED handle
References LED_Object::brightness, LED_Config::hwAttrs, LED_BRIGHTNESS_MIN, LED_GPIO_CONTROLLED, LED_OFF, LED_setBrightnessLevel(), LED_STATE_BLINKING, LED_STATE_OFF, LED_Object::ledType, LED_Config::object, LED_Object::rawState, and LED_Object::state.
Referenced by LED_close(), LED_stopBlinking(), and LED_toggle().
LED_setOn()
bool LED_setOn (LED_Handle ledHandle, uint16_t brightness)
Function to turn on a LED.
Parameters
ledHandle A LED handle
brightness Brightness level in terms of percentage 0-100 %
Returns
true on success or false upon failure.
References LED_Config::hwAttrs, LED_GPIO_CONTROLLED, LED_ON, LED_setBrightnessLevel(), LED_STATE_BLINKING, LED_STATE_ON, LED_Object::ledType, LED_Config::object, LED_Object::rawState, and LED_Object::state.
Referenced by LED_toggle().
LED_startBlinking()
void LED_startBlinking (LED_Handle ledHandle, uint16_t blinkPeriod)
Function to start a LED blinking.
Parameters
ledHandle A LED handle
blinkPeriod blinkPeriod(in ms) with which LED will blink maximum togglePeriod will be 65 seconds(=65535/0xFFFF)
References LED_Object::blinkPeriod, LED_BLINKPERIOD_ZERO, LED_STATE_BLINKING, LED_Config::object, LED_Object::state, and LED_Object::timer.
LED_stopBlinking()
void LED_stopBlinking (LED_Handle ledHandle)
Function to stop a LED blinking.
Parameters
ledHandle A LED handle
References LED_setOff(), LED_STATE_BLINKING, LED_STATE_OFF, LED_Config::object, LED_Object::state, and LED_Object::timer.
Referenced by LED_close().
LED_toggle()
void LED_toggle (LED_Handle ledHandle)
Function to toggle a LED.
Parameters
ledHandle A LED handle
References LED_Object::brightness, LED_setOff(), LED_setOn(), LED_STATE_OFF, LED_STATE_ON, LED_Config::object, and LED_Object::rawState.
Copyright 2017, Texas Instruments Incorporated