SAILAPIGuide: led.c File Reference
led.c File Reference
#include <ti/drivers/GPIO.h>
#include <ti/drivers/PWM.h>
#include <ti/sail/led/led.h>
Macros
#define LED_BLINKPERIOD_ZERO 0U /* To indicate no blinking operation*/
#define LED_PWMPERIOD_1MS 1000U /* Default PWM period is 1 ms*/
Functions
void LED_close (LED_Handle ledHandle)
Function to close a LED specified by the LED handle.
LED_State LED_getState (LED_Handle ledHandle)
Function to get LED state.
void LED_init ()
Function to initialize LED driver.
LED_Handle LED_open (unsigned int ledIndex, LED_Params *params)
Function to open an instance of LED.
void LED_initParams (LED_Params *params)
Function to initialize a LED_Params struct to its defaults.
bool LED_setBrightnessLevel (LED_Handle ledHandle, uint16_t level)
Function to set brightness level of a LED.
void LED_setOff (LED_Handle ledHandle)
Function to turn off a LED.
bool LED_setOn (LED_Handle ledHandle, uint16_t brightness)
Function to turn on a LED.
void LED_startBlinking (LED_Handle ledHandle, uint16_t blinkPeriod)
Function to start a LED blinking.
void LED_stopBlinking (LED_Handle ledHandle)
Function to stop a LED blinking.
void LED_toggle (LED_Handle ledHandle)
Function to toggle a LED.
Variables
const LED_Params LED_defaultParams
LED_Config LED_config []
Macro Definition Documentation
LED_BLINKPERIOD_ZERO
#define LED_BLINKPERIOD_ZERO 0U /* To indicate no blinking operation*/
Referenced by LED_startBlinking().
LED_PWMPERIOD_1MS
#define LED_PWMPERIOD_1MS 1000U /* Default PWM period is 1 ms*/
Function Documentation
LED_close()
void LED_close (LED_Handle ledHandle)
Function to close a LED specified by the LED handle.
The LED close API to close the LED instance specified by ledHandle.
This call will destruct associated timer if running and turn off LED, can be hooked up with Power Down sequence in system.
Precondition
LED_open() had to be called first.
Parameters
ledHandle A LED_Handle returned from LED_open()
References LED_setOff(), LED_stopBlinking(), LED_Config::object, and LED_Object::timer.
LED_getState()
LED_State LED_getState (LED_Handle ledHandle)
Function to get LED state.
This function may be useful in scenarios if a LED state(ON/OFF/BLINKING) is tied with some system warning/alerts
Parameters
ledHandle A LED_Handle returned from LED_open()
Returns
The LED State
References LED_Config::object, and LED_Object::state.
LED_init()
void LED_init ()
Function to initialize LED driver.
This function will initialize the LED driver.
LED_open()
LED_Handle LED_open (unsigned int ledIndex, LED_Params * params)
Function to open an instance of LED.
Function to initialize a given LED specified by the particular index value.LED parameters must be setup and PWM handle opened(only for PWM controlled LED type) before this call.
User may request to set LED into particular state, for ex: open an handle and start blinking that LED or just turn in ON or OFF
Precondition
LED_init() has to be called first
Parameters
ledIndex Logical led number indexed into the LED_config table
*params A pointer to LED_Params structure. If NULL, it will use default values.
Returns
A LED_Handle on success, or a NULL on failure.
See also
LED_init()
LED_Params_init()
LED_close()
LED_initParams()
void LED_initParams (LED_Params * params)
Function to initialize a LED_Params struct to its defaults.
Parameters
params A pointer to LED_Params structure for initialization.
Default values are: ledType = LED_GPIO_CONTROLLED brightness = LED_BRIGHTNESS_MAX
References LED_defaultParams.
LED_setBrightnessLevel()
bool LED_setBrightnessLevel (LED_Handle ledHandle, uint16_t level)
Function to set brightness level of a LED.
Ignores brightness settings if LED is not PWM controlled
Parameters
ledHandle A LED handle
level Brightness level in terms of percentage 0-100 %
Returns
true on success or false upon failure.
References LED_Object::brightness, LED_BRIGHTNESS_MAX, LED_GPIO_CONTROLLED, LED_PWM_CONTROLLED, LED_Object::ledType, LED_Config::object, LED_Object::pwmHandle, and LED_Object::pwmPeriod.
Referenced by LED_setOff(), and LED_setOn().
LED_setOff()
void LED_setOff (LED_Handle ledHandle)
Function to turn off a LED.
Parameters
ledHandle A LED handle
References LED_Object::brightness, LED_Config::hwAttrs, LED_BRIGHTNESS_MIN, LED_GPIO_CONTROLLED, LED_OFF, LED_setBrightnessLevel(), LED_STATE_BLINKING, LED_STATE_OFF, LED_Object::ledType, LED_Config::object, LED_Object::rawState, and LED_Object::state.
Referenced by LED_close(), LED_stopBlinking(), and LED_toggle().
LED_setOn()
bool LED_setOn (LED_Handle ledHandle, uint16_t brightness)
Function to turn on a LED.
Parameters
ledHandle A LED handle
brightness Brightness level in terms of percentage 0-100 %
Returns
true on success or false upon failure.
References LED_Config::hwAttrs, LED_GPIO_CONTROLLED, LED_ON, LED_setBrightnessLevel(), LED_STATE_BLINKING, LED_STATE_ON, LED_Object::ledType, LED_Config::object, LED_Object::rawState, and LED_Object::state.
Referenced by LED_toggle().
LED_startBlinking()
void LED_startBlinking (LED_Handle ledHandle, uint16_t blinkPeriod)
Function to start a LED blinking.
Parameters
ledHandle A LED handle
blinkPeriod blinkPeriod(in ms) with which LED will blink maximum togglePeriod will be 65 seconds(=65535/0xFFFF)
References LED_Object::blinkPeriod, LED_BLINKPERIOD_ZERO, LED_STATE_BLINKING, LED_Config::object, LED_Object::state, and LED_Object::timer.
LED_stopBlinking()
void LED_stopBlinking (LED_Handle ledHandle)
Function to stop a LED blinking.
Parameters
ledHandle A LED handle
References LED_setOff(), LED_STATE_BLINKING, LED_STATE_OFF, LED_Config::object, LED_Object::state, and LED_Object::timer.
Referenced by LED_close().
LED_toggle()
void LED_toggle (LED_Handle ledHandle)
Function to toggle a LED.
Parameters
ledHandle A LED handle
References LED_Object::brightness, LED_setOff(), LED_setOn(), LED_STATE_OFF, LED_STATE_ON, LED_Config::object, and LED_Object::rawState.
Variable Documentation
LED_defaultParams
const LED_Params LED_defaultParams
Initial value:
= {
        LED_GPIO_CONTROLLED,
        NULL,
        LED_PWMPERIOD_1MS,
        LED_BRIGHTNESS_MIN,
        LED_STATE_OFF,
        LED_BLINKPERIOD_ZERO
}
Referenced by LED_initParams().
LED_config
LED_Config LED_config[]
Copyright 2017, Texas Instruments Incorporated