SAILAPIGuide: pga460.h File Reference
pga460.h File Reference
Detailed Description
PGA460-Q1 Automotive Ultrasonic Signal Processor and Transducer Driver.
============================================================================
The PGA460-Q1 is Automotive Ultrasonic Signal Processor and Transducer Driver.It is interfaced to the MCU using UART/OWU (ONE WIRE UART)/TCI (TIME COMMAND INTERFACE).The current implementation supports only UART mode.
The PGA460 header file should be included in an application as follows:
#include <ti/sail/pga460/pga460.h>
Operation
The PGA460 driver simplifies using a PGA460 Automotive Ultrasonic Signal Processor and Transducer Driver. A PGA460_config array should be defined by the application. The PGA460_config array should contain pointers to a defined PGA460_HwAttrs and allocated array for the PGA460_Object structures. PGA460_init() must be called prior to using PGA460_open().
The APIs in this driver serve as an interface to a DPL(Driver Porting Layer) The specific implementations are responsible for creating all the RTOS specific primitives to allow for thread-safe operation.
This driver has no dynamic memory allocation.
Defining PGA460_Config, PGA460_Object and PGA460_HwAttrs
Each structure must be defined by the application. The following example is for a MSP432 in which an PGA460 sensor is setup. The following declarations are placed in "MSP_EXP432P401R.h" and "MSP_EXP432P401R.c" respectively.
"MSP_EXP432P401R.h"
typedef enum MSP_EXP432P401R_PGA460Name {
    MSP_EXP432P401R_PGA460_0 = 0, // Sensor for measuring distance from obstuction.
    MSP_EXP432P401R_PGA460COUNT
} MSP_EXP432P401R_PGA460Name;
"MSP_EXP432P401R.c"
#include <ti/sail/pga460/pga460.h>
PGA460_Object PGA460_object[MSP_EXP432P401R_PGA460COUNT];
const PGA460_HWAttrs PGA460_hwAttrs[MSP_EXP432P401R_PGA460COUNT] = {
    {
        .uartAddress = 0 // 0 is the address of interfaced PGA460 device
    }
};
const PGA460_Config PGA460_config[] = {
    {
        .hwAttrs = &PGA460_hwAttrs[0],
        .objects = &PGA460_object[0],
    },
    {NULL, NULL},
};
const uint_least8_t PGA460_count = MSP_EXP432P401R_PGA460COUNT;
Opening a UART Handle
The UART controller must be in blocking mode. This will seamlessly allow for multiple UART endpoints without conflicting callback functions. The UART_open() call requires a configured index. This index must be defined by the application in accordance to the UART driver. The default transfer mode for an UART_Params structure is UART_MODE_BLOCKING. In the example below, the transfer mode is set explicitly for clarity.The data mode setting is binary. Additionally, the PGA460 hardware is capable of communicating in range 2400 bps to 115200 bps
#include <ti/drivers/UART.h>
UART_Handle uartHandle;
UART_Params uartParams;
UART_Params_init(&uartParams);
uartParams.baudRate  = 115200;
uartParams.writeMode = UART_MODE_BLOCKING;
uartParams.readDataMode = UART_DATA_BINARY;
uartParams.writeDataMode = UART_DATA_BINARY;
uartParams.readEcho = UART_ECHO_OFF;
uartHandle = UART_open(Board_PGA460_UART, &uartParams);
Opening a PGA460 with default parameters
The PGA460_open() call must be made in a task context.
#include <ti/sail/pga460/pga460.h>
PGA460_Handle handle;
PGA460_init();
handle = PGA460_open(Board_PGA460_PARK, uartHandle, NULL);
#include <stdbool.h>
#include <ti/drivers/UART.h>
Data Structures
struct PGA460_Config
PGA460 configuration.
struct PGA460_UARTHWAttrs
Hardware specific settings for a PGA460(UART).
struct PGA460_Object
Members should not be accessed by the application.
struct PGA460_Params
PGA460 Parameters.
struct PGA460_EEBW
struct PGA460_THRBW
struct PGA460_RW
struct PGA460_RR
struct PGA460_TVGBW
struct PGA460_P1BL
struct PGA460_P2BL
struct PGA460_UMR
struct PGA460_SD
struct PGA460_TNLM
struct PGA460_TNLR
struct PGA460_ULMResults
Macros
#define PGA460_USER_DATA1 0x0U
#define PGA460_USER_DATA2 0x1U
#define PGA460_USER_DATA3 0x2U
#define PGA460_USER_DATA4 0x3U
#define PGA460_USER_DATA5 0x4U
#define PGA460_USER_DATA6 0x5U
#define PGA460_USER_DATA7 0x6U
#define PGA460_USER_DATA8 0x7U
#define PGA460_USER_DATA9 0x8U
#define PGA460_USER_DATA10 0x9U
#define PGA460_USER_DATA11 0xAU
#define PGA460_USER_DATA12 0xBU
#define PGA460_USER_DATA13 0xCU
#define PGA460_USER_DATA14 0xDU
#define PGA460_USER_DATA15 0xEU
#define PGA460_USER_DATA16 0xFU
#define PGA460_USER_DATA17 0x10U
#define PGA460_USER_DATA18 0x11U
#define PGA460_USER_DATA19 0x12U
#define PGA460_USER_DATA20 0x13U
#define PGA460_TVGAIN0 0x14U
#define PGA460_TVGAIN1 0x15U
#define PGA460_TVGAIN2 0x16U
#define PGA460_TVGAIN3 0x17U
#define PGA460_TVGAIN4 0x18U
#define PGA460_TVGAIN5 0x19U
#define PGA460_TVGAIN6 0x1AU
#define PGA460_INIT_GAIN 0x1BU
#define PGA460_FREQUENCY 0x1CU
#define PGA460_DEADTIME 0x1DU
#define PGA460_PULSE_P1 0x1EU
#define PGA460_PULSE_P2 0x1FU
#define PGA460_CURR_LIM_P1 0x20U
#define PGA460_CURR_LIM_P2 0x21U
#define PGA460_REC_LENGTH 0x22U
#define PGA460_FREQ_DIAG 0x23U
#define PGA460_SAT_FDIAG_TH 0x24U
#define PGA460_FVOLT_DEC 0x25U
#define PGA460_DECPL_TEMP 0x26U
#define PGA460_DSP_SCALE 0x27U
#define PGA460_TEMP_TRIM 0x28U
#define PGA460_P1_GAIN_CTRL 0x29U
#define PGA460_P2_GAIN_CTRL 0x2AU
#define PGA460_EE_CRC 0x2BU
#define PGA460_EE_CNTRL 0x40U
#define PGA460_BPF_A2_MSB 0x41U
#define PGA460_BPF_A2_LSB 0x42U
#define PGA460_BPF_A3_MSB 0x43U
#define PGA460_BPF_A3_LSB 0x44U
#define PGA460_BPF_B1_MSB 0x45U
#define PGA460_BPF_B1_LSB 0x46U
#define PGA460_LPF_A2_MSB 0x47U
#define PGA460_LPF_A2_LSB 0x48U
#define PGA460_LPF_B1_MSB 0x49U
#define PGA460_LPF_B1_LSB 0x4AU
#define PGA460_TEST_MUX 0x4BU
#define PGA460_DEV_STAT0 0x4CU
#define PGA460_DEV_STAT1 0x4DU
#define PGA460_P1_THR_0 0x5FU
#define PGA460_P1_THR_1 0x60U
#define PGA460_P1_THR_2 0x61U
#define PGA460_P1_THR_3 0x62U
#define PGA460_P1_THR_4 0x63U
#define PGA460_P1_THR_5 0x64U
#define PGA460_P1_THR_6 0x65U
#define PGA460_P1_THR_7 0x66U
#define PGA460_P1_THR_8 0x67U
#define PGA460_P1_THR_9 0x68U
#define PGA460_P1_THR_10 0x69U
#define PGA460_P1_THR_11 0x6AU
#define PGA460_P1_THR_12 0x6BU
#define PGA460_P1_THR_13 0x6CU
#define PGA460_P1_THR_14 0x6DU
#define PGA460_P1_THR_15 0x6EU
#define PGA460_P2_THR_0 0x6FU
#define PGA460_P2_THR_1 0x70U
#define PGA460_P2_THR_2 0x71U
#define PGA460_P2_THR_3 0x72U
#define PGA460_P2_THR_4 0x73U
#define PGA460_P2_THR_5 0x74U
#define PGA460_P2_THR_6 0x75U
#define PGA460_P2_THR_7 0x76U
#define PGA460_P2_THR_8 0x77U
#define PGA460_P2_THR_9 0x78U
#define PGA460_P2_THR_10 0x79U
#define PGA460_P2_THR_11 0x7AU
#define PGA460_P2_THR_12 0x7BU
#define PGA460_P2_THR_13 0x7CU
#define PGA460_P2_THR_14 0x7DU
#define PGA460_P2_THR_15 0x7EU
#define PGA460_THR_CRC 0x7FU
#define PGA460_UARTERROR_DEVICEBUSY 0x41U
#define PGA460_UARTERROR_BITRATE 0x42U
#define PGA460_UARTERROR_SYNCFIELDWIDTH 0x44U
#define PGA460_UARTERROR_INVALIDCHECKSUM 0x48U
#define PGA460_UARTERROR_INVALIDCOMMAND 0x50U
#define PGA460_UARTERROR_GENCOMMUNICATION 0x60U
#define PGA460_SYSDIAGERROR_DEVICEBUSY 0x41U
#define PGA460_SYSDIAGERROR_THRSETTINGSCRC 0x42U
#define PGA460_SYSDIAGERROR_FREQDIAG 0x44U
#define PGA460_SYSDIAGERROR_VOLTAGEDIAT 0x48U
#define PGA460_SYSDIAGERROR_EEPROMTRIMCRC 0x60U
#define PGA460_CHECKSUMERRORFLAG 0x0100U
#define PGA460_ERROR_OK 0x40U
Typedefs
typedef uint16_t PGA460_respErrorStatusFlags
typedef struct PGA460_Config * PGA460_Handle
A handle that is returned from a PGA460_open() call.
typedef enum PGA460_communicationInterface PGA460_communicationInterface
Communication Interface used with PGA460-Q1.
typedef enum PGA460_ultrasonicSensorType PGA460_ultrasonicSensorType
Defines for ultrasonic sensors.
typedef enum PGA460_preset PGA460_preset
Defines for PGA460 presets.
typedef enum PGA460_threshold PGA460_threshold
Defines for PGA460 threshold values.
typedef enum PGA460_tvggain PGA460_tvgain
Defines for PGA460 time varying gain values.
typedef enum PGA460_lpmTime PGA460_lpmTime
Defines for PGA460 low power mode time.
typedef enum PGA460_afegain PGA460_afegain
Defines for PGA460 AFE Gain.
typedef enum PGA460_diagnostic PGA460_diagnostic
Defines for diagnostic commands.
typedef enum PGA460_broadcast PGA460_broadcast
Defines for broadcast enable disable.
typedef enum PGA460_commandCode PGA460_commandCode
[4:0] of UART command field.
typedef struct PGA460_Config PGA460_Config
PGA460 configuration.
typedef struct PGA460_UARTHWAttrs PGA460_UARTHWAttrs
Hardware specific settings for a PGA460(UART).
typedef struct PGA460_Object PGA460_Object
Members should not be accessed by the application.
typedef struct PGA460_Params PGA460_Params
PGA460 Parameters.
typedef struct PGA460_EEBW PGA460_EEBW
typedef struct PGA460_THRBW PGA460_THRBW
typedef struct PGA460_RW PGA460_RW
typedef struct PGA460_RR PGA460_RR
typedef struct PGA460_TVGBW PGA460_TVGBW
typedef struct PGA460_P1BL PGA460_P1BL
typedef struct PGA460_P2BL PGA460_P2BL
typedef struct PGA460_UMR PGA460_UMR
typedef struct PGA460_SD PGA460_SD
typedef struct PGA460_TNLM PGA460_TNLM
typedef struct PGA460_TNLR PGA460_TNLR
typedef struct PGA460_ULMResults PGA460_ULMResults
Enumerations
enum PGA460_communicationInterface { PGA460_communicationInterface_UART = 0x00U, PGA460_communicationInterface_OWU = 0x01U, PGA460_communicationInterface_TCI = 0x02U }
Communication Interface used with PGA460-Q1.
enum PGA460_ultrasonicSensorType { PGA460_ultrasonicSensorType_MA58MF147N = 0x00U, PGA460_ultrasonicSensorType_MA40H1SR = 0x01U, PGA460_ultrasonicSensorType_CUSTOM = 0x02U }
Defines for ultrasonic sensors.
enum PGA460_preset { PGA460_presets_PRESET1 = 0x00, PGA460_presets_PRESET2 = 0x01 }
Defines for PGA460 presets.
enum PGA460_threshold { PGA460_threshold_25 = 0x00, PGA460_threshold_50 = 0x01, PGA460_threshold_75 = 0x02, PGA460_threshold_custom = 0x03U }
Defines for PGA460 threshold values.
enum PGA460_tvggain { PGA460_tvgain_25 = 0x00U, PGA460_tvgain_50 = 0x01U, PGA460_tvgain_75 = 0x02U, PGA460_tvgain_custom = 0x03U }
Defines for PGA460 time varying gain values.
enum PGA460_lpmTime { PGA460_lpmTime_250ms = 0x00U, PGA460_lpmTime_500ms = 0x01U, PGA460_lpmTime_1s = 0x02U, PGA460_lpmTime_4s = 0x03U }
Defines for PGA460 low power mode time.
enum PGA460_afegain { PGA460_afegain_58_90 = 0x00U, PGA460_afegain_52_84 = 0x01U, PGA460_afegain_46_78 = 0x02U, PGA460_afegain_32_64 = 0x03U }
Defines for PGA460 AFE Gain.
enum PGA460_diagnostic { PGA460_diagnostic_TF = 0x00U, PGA460_diagnostic_DPT = 0x01U, PGA460_diagnostic_TLM = 0x02U, PGA460_diagnostic_NLM = 0x03U }
Defines for diagnostic commands.
enum PGA460_broadcast { PGA460_broadcast_Disable = 0x00U, PGA460_broadcast_Enable = 0x01U }
Defines for broadcast enable disable.
enum PGA460_commandCode {
PGA460_commandCode_P1BL = 0x00U, PGA460_commandCode_P2BL = 0x01U, PGA460_commandCode_P1LO = 0x02U, PGA460_commandCode_P2LO = 0x03U,
PGA460_commandCode_TNLM = 0x04U, PGA460_commandCode_UMR = 0x05U, PGA460_commandCode_TNLR = 0x06U, PGA460_commandCode_TEDD = 0x07U,
PGA460_commandCode_SD = 0x08U, PGA460_commandCode_SRR = 0x09U, PGA460_commandCode_SRW = 0x0AU, PGA460_commandCode_EEBR = 0x0BU,
PGA460_commandCode_EEBW = 0x0CU, PGA460_commandCode_TVGBR = 0x0DU, PGA460_commandCode_TVGBW = 0x0EU, PGA460_commandCode_THRBR = 0x0FU,
PGA460_commandCode_THRBW = 0x10U, PGA460_commandCode_BC_P1BL = 0x11U, PGA460_commandCode_BC_P2BL = 0x12U, PGA460_commandCode_BC_P1LO = 0x13U,
PGA460_commandCode_BC_P2LO = 0x14U, PGA460_commandCode_BC_TNLM = 0x15U, PGA460_commandCode_BC_SRW = 0x16U, PGA460_commandCode_BC_EEBW = 0x17U,
PGA460_commandCode_BC_TVGBW = 0x18U, PGA460_commandCode_BC_THRBW = 0x19U, PGA460_commandCode_none = 0x1AU
}
[4:0] of UART command field.
Functions
bool PGA460_close (PGA460_Handle handle)
Function to close a PGA460 sensor specified by the PGA460 handle.
void PGA460_init ()
Function to initialize PGA460 driver.
PGA460_Handle PGA460_open (unsigned int index, void *comInterfaceHandle, PGA460_Params *params)
Function to open a given PGA460 sensor.
bool PGA460_configure (PGA460_Handle handle, PGA460_ultrasonicSensorType sensorType, const PGA460_EEBW *eebw, PGA460_broadcast broadcastEnable)
Function to configure initial settings of the PGA460.
bool PGA460_setThreshholds (PGA460_Handle handle, PGA460_threshold threshold, const PGA460_THRBW *thrbw, PGA460_broadcast broadcastEnable)
Function to set threshold levels for PGA460.
bool PGA460_setTimeVaryingGain (PGA460_Handle handle, PGA460_tvgain tvgain, const PGA460_TVGBW *tvgbw, PGA460_broadcast broadcastEnable)
Function to set time varying gain values for PGA460.
bool PGA460_setAFEGain (PGA460_Handle handle, PGA460_afegain afegain, PGA460_broadcast broadcastEnable)
Function to set AFEGAIN for PGA460.
bool PGA460_burstAndListenCmd (PGA460_Handle handle, PGA460_preset preset, uint8_t numOfObjects, PGA460_broadcast broadcastEnable)
Function to start Burst and Listen command for specific preset.
bool PGA460_ListenOnlyCmd (PGA460_Handle handle, PGA460_preset preset, uint8_t numOfObjects, PGA460_broadcast broadcastEnable)
Function to start Burst and Listen command for specific preset.
bool PGA460_getMeasurements (PGA460_Handle handle, PGA460_ULMResults *measurementResults, uint8_t numberOfObjects, PGA460_respErrorStatusFlags *errFlags)
Function to start Burst and Listen command for specific preset.
bool PGA460_enableEchoDataDump (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to set echo dump bit.
bool PGA460_disableEchoDataDump (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to clear echo dump enable bit.
bool PGA460_getEchoDataDump (PGA460_Handle handle, uint8_t *echoDataDump, PGA460_respErrorStatusFlags *errFlags)
Function to start Burst and Listen command for specific preset.
bool PGA460_runDiagnostic (PGA460_Handle handle, PGA460_diagnostic diagnostic, double *diagResult, PGA460_respErrorStatusFlags *errFlags)
Function to run diagnostics on PGA460.
bool PGA460_writeRegister (PGA460_Handle handle, PGA460_RW *rw, PGA460_broadcast broadcastEnable)
Function to write to register on PGA460.
bool PGA460_readRegister (PGA460_Handle handle, uint8_t regAddr, uint8_t *regData, PGA460_respErrorStatusFlags *errFlags)
Function to read register on PGA460. (single register read)
bool PGA460_burnEEPROM (PGA460_Handle handle)
Function to burn EEPROM of PGA460.
bool PGA460_setLowPowerMode (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to move PGA460 to low power mode.
void PGA460_Params_init (PGA460_Params *params)
Function to initialize a PGA460_Params struct to its defaults.
Typedef Documentation
PGA460_respErrorStatusFlags
typedef uint16_t PGA460_respErrorStatusFlags
PGA460_Handle
typedef struct PGA460_Config* PGA460_Handle
A handle that is returned from a PGA460_open() call.
PGA460_communicationInterface
typedef enum PGA460_communicationInterface PGA460_communicationInterface
Communication Interface used with PGA460-Q1.
The enumeration describes about the communication interface used with the PGA460-Q1
The PGA460-Q1 has 3 possible communication interfaces, UART, OWU(one wire uart) and TCI(time command interface). Currently only UART is supported.
PGA460_ultrasonicSensorType
typedef enum PGA460_ultrasonicSensorType PGA460_ultrasonicSensorType
Defines for ultrasonic sensors.
The Enumeration is used for identifying ultrasonic sensors.
See also
PGA460_configure
PGA460_preset
typedef enum PGA460_preset PGA460_preset
Defines for PGA460 presets.
The enumeration is used for identifying PGA460 presets.
See also
PGA460_setThreshholds
PGA460_threshold
typedef enum PGA460_threshold PGA460_threshold
Defines for PGA460 threshold values.
The enumeration is used for specifying threshold values for presets.
See also
PGA460_setThreshholds
PGA460_tvgain
typedef enum PGA460_tvggain PGA460_tvgain
Defines for PGA460 time varying gain values.
The wnumeration is used for specifying time varying gain values.
See also
PGA460_setTimeVaryingGain
PGA460_lpmTime
typedef enum PGA460_lpmTime PGA460_lpmTime
Defines for PGA460 low power mode time.
The enumeration is used for specifying low power mode enter time
See also
PGA460_setLowPowerMode
PGA460_afegain
typedef enum PGA460_afegain PGA460_afegain
Defines for PGA460 AFE Gain.
The enumeration is used for specifying analog front end gain.
See also
PGA460_setAFEGain
PGA460_diagnostic
typedef enum PGA460_diagnostic PGA460_diagnostic
Defines for diagnostic commands.
The enumeration is used for specifying diagnostic command.
See also
PGA460_runDiagnostic
PGA460_broadcast
typedef enum PGA460_broadcast PGA460_broadcast
Defines for broadcast enable disable.
The enumeration is used for specifying broadcast enable/disable
PGA460_commandCode
typedef enum PGA460_commandCode PGA460_commandCode
[4:0] of UART command field.
The enumeration describes field [4:0} of UART command field.
The UART command field consists of 8 bits. The [4:0] field forms the UART command field and [7:5] forms the UART address field. The address field has to be appended to this field so as to create the UART Command.
PGA460_Config
typedef struct PGA460_Config PGA460_Config
PGA460 configuration.
The PGA460_Config structure contains a set of pointers used to characterize the PGA460 driver implementation.
This structure needs to be defined and provided by the application.
PGA460_UARTHWAttrs
typedef struct PGA460_UARTHWAttrs PGA460_UARTHWAttrs
Hardware specific settings for a PGA460(UART).
This structure should be defined and provided by the application.
PGA460_Object
typedef struct PGA460_Object PGA460_Object
Members should not be accessed by the application.
PGA460_Params
typedef struct PGA460_Params PGA460_Params
PGA460 Parameters.
PGA460 parameters are used with the PGA460_open() call. Default values for these parameters are set using PGA460_Params_init().
See also
PGA460_Params_init()
PGA460_EEBW
typedef struct PGA460_EEBW PGA460_EEBW
EEPROM bulk write command format.
PGA460_THRBW
typedef struct PGA460_THRBW PGA460_THRBW
Threshold bulk write command format.
PGA460_RW
typedef struct PGA460_RW PGA460_RW
Register write command format.
PGA460_RR
typedef struct PGA460_RR PGA460_RR
Register read command format.
PGA460_TVGBW
typedef struct PGA460_TVGBW PGA460_TVGBW
Time varying gain bulk write command format.
PGA460_P1BL
typedef struct PGA460_P1BL PGA460_P1BL
Burst Listen Preset 1
PGA460_P2BL
typedef struct PGA460_P2BL PGA460_P2BL
Burst Listen Preset 2
PGA460_UMR
typedef struct PGA460_UMR PGA460_UMR
Ultrasonic Measurement Results command format.
PGA460_SD
typedef struct PGA460_SD PGA460_SD
System Diagnostics command format.
PGA460_TNLM
typedef struct PGA460_TNLM PGA460_TNLM
Temperature and Noise level measurement command format
PGA460_TNLR
typedef struct PGA460_TNLR PGA460_TNLR
Temperature and Noise Level Result command format.
PGA460_ULMResults
typedef struct PGA460_ULMResults PGA460_ULMResults
Ultrasonic measurement results for the each object detected
Enumeration Type Documentation
PGA460_communicationInterface
enum PGA460_communicationInterface
Communication Interface used with PGA460-Q1.
The enumeration describes about the communication interface used with the PGA460-Q1
The PGA460-Q1 has 3 possible communication interfaces, UART, OWU(one wire uart) and TCI(time command interface). Currently only UART is supported.
Enumerator
PGA460_communicationInterface_UART
UART interface
PGA460_communicationInterface_OWU
One Wire UART interface
PGA460_communicationInterface_TCI
Time Command Interface
PGA460_ultrasonicSensorType
enum PGA460_ultrasonicSensorType
Defines for ultrasonic sensors.
The Enumeration is used for identifying ultrasonic sensors.
See also
PGA460_configure
Enumerator
PGA460_ultrasonicSensorType_MA58MF147N
murata MA58MF147N
PGA460_ultrasonicSensorType_MA40H1SR
murata MA40H1SR
PGA460_ultrasonicSensorType_CUSTOM
User specified settings will be used.
PGA460_preset
enum PGA460_preset
Defines for PGA460 presets.
The enumeration is used for identifying PGA460 presets.
See also
PGA460_setThreshholds
Enumerator
PGA460_presets_PRESET1
PRESET1 of PGA460.
PGA460_presets_PRESET2
PRESET2 of PGA460.
PGA460_threshold
enum PGA460_threshold
Defines for PGA460 threshold values.
The enumeration is used for specifying threshold values for presets.
See also
PGA460_setThreshholds
Enumerator
PGA460_threshold_25
25% threshold values.
PGA460_threshold_50
50% threshold values.
PGA460_threshold_75
75% threshold values.
PGA460_threshold_custom
User specified threshold values.
PGA460_tvggain
enum PGA460_tvggain
Defines for PGA460 time varying gain values.
The wnumeration is used for specifying time varying gain values.
See also
PGA460_setTimeVaryingGain
Enumerator
PGA460_tvgain_25
25% tvggain values.
PGA460_tvgain_50
50% tvggain values.
PGA460_tvgain_75
75% tvggain values.
PGA460_tvgain_custom
User specified tvggain values.
PGA460_lpmTime
enum PGA460_lpmTime
Defines for PGA460 low power mode time.
The enumeration is used for specifying low power mode enter time
See also
PGA460_setLowPowerMode
Enumerator
PGA460_lpmTime_250ms
250 ms low power mode enter timer.
PGA460_lpmTime_500ms
500 ms low power mode enter timer.
PGA460_lpmTime_1s
1 s low power mode enter timer.
PGA460_lpmTime_4s
4 s low power mode enter timer.
PGA460_afegain
enum PGA460_afegain
Defines for PGA460 AFE Gain.
The enumeration is used for specifying analog front end gain.
See also
PGA460_setAFEGain
Enumerator
PGA460_afegain_58_90
58 to 90db AFE gain.
PGA460_afegain_52_84
52 to 84db AFE gain.
PGA460_afegain_46_78
52 to 84db AFE gain.
PGA460_afegain_32_64
52 to 84db AFE gain.
PGA460_diagnostic
enum PGA460_diagnostic
Defines for diagnostic commands.
The enumeration is used for specifying diagnostic command.
See also
PGA460_runDiagnostic
Enumerator
PGA460_diagnostic_TF
Transducer frequency.
PGA460_diagnostic_DPT
Decay Period time.
PGA460_diagnostic_TLM
Temperature Level measurement.
PGA460_diagnostic_NLM
Noise Level Measurement.
PGA460_broadcast
enum PGA460_broadcast
Defines for broadcast enable disable.
The enumeration is used for specifying broadcast enable/disable
Enumerator
PGA460_broadcast_Disable
Broadcast disable enum
PGA460_broadcast_Enable
Broadcast enable enum
PGA460_commandCode
enum PGA460_commandCode
[4:0] of UART command field.
The enumeration describes field [4:0} of UART command field.
The UART command field consists of 8 bits. The [4:0] field forms the UART command field and [7:5] forms the UART address field. The address field has to be appended to this field so as to create the UART Command.
Enumerator
PGA460_commandCode_P1BL
PGA460_commandCode_P2BL
PGA460_commandCode_P1LO
PGA460_commandCode_P2LO
PGA460_commandCode_TNLM
PGA460_commandCode_UMR
PGA460_commandCode_TNLR
PGA460_commandCode_TEDD
PGA460_commandCode_SD
PGA460_commandCode_SRR
PGA460_commandCode_SRW
PGA460_commandCode_EEBR
PGA460_commandCode_EEBW
PGA460_commandCode_TVGBR
PGA460_commandCode_TVGBW
PGA460_commandCode_THRBR
PGA460_commandCode_THRBW
PGA460_commandCode_BC_P1BL
PGA460_commandCode_BC_P2BL
PGA460_commandCode_BC_P1LO
PGA460_commandCode_BC_P2LO
PGA460_commandCode_BC_TNLM
PGA460_commandCode_BC_SRW
PGA460_commandCode_BC_EEBW
PGA460_commandCode_BC_TVGBW
PGA460_commandCode_BC_THRBW
PGA460_commandCode_none
Function Documentation
PGA460_close()
bool PGA460_close (PGA460_Handle handle)
Function to close a PGA460 sensor specified by the PGA460 handle.
The instance of the PGA460 will be closed. All the relevant data structures will be invalid after this call.
Precondition
PGA460_open() had to be called first.
Parameters
handle A PGA460_Handle returned from PGA460_open()
Returns
true on success or false upon failure.
References PGA460_Object::comInterfaceHandle, and PGA460_Config::object.
PGA460_init()
void PGA460_init ()
Function to initialize PGA460 driver.
This function will initialize the PGA460 driver. This function must also be called before any other PGA460 module APIs.
PGA460_open()
PGA460_Handle PGA460_open (unsigned int index, void * comInterfaceHandle, PGA460_Params * params)
Function to open a given PGA460 sensor.
Function to initialize a given PGA460 sensor specified by the particular index value. This function must be called from a task context. If one intends to use the IO pin for TCI, OWU communication, then that has to be specified in the PGA460_Params structure. Additionally, a gpioIndex must be setup and specified in the PGA460_HWAttrs structure.
The user should ensure that each sensor has its own UART address. when UART/USART/OWU communication interface is used and PGA460Index.
Precondition
PGA460_init() has to be called first
Parameters
PGA460Index Logical sensor number for the PGA460 indexed into the PGA460_config table
comInterfaceHandle An communication interface handler(SPI/UART)
params A pointer to PGA460_Params structure. If NULL, it will use default values.
Returns
A PGA460_Handle on success, or a NULL on failure.
See also
PGA460_init()
PGA460_Params_init()
PGA460_close()
PGA460_configure()
bool PGA460_configure (PGA460_Handle handle, PGA460_ultrasonicSensorType sensorType, const PGA460_EEBW * eebw, PGA460_broadcast broadcastEnable)
Function to configure initial settings of the PGA460.
Function to configure PGA460 to recommended settings for the specified ultrasonic sensor type.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
sensorType User has to specify the sensor type. Currently three settings are supported. If the setting is CUSTOM then the onus is on user to provide initialized eebw structure.
eebw A pointer to PGA460_EEBW structure.
broadcastEnable This can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if execution of the API is not successful.
See also
PGA460_ultrasonicSensorType
References PGA460_Object::comInterface, eepromMA40H1SR, eepromMA58MF147N, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_EEBW, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_ultrasonicSensorType_CUSTOM, PGA460_ultrasonicSensorType_MA40H1SR, PGA460_ultrasonicSensorType_MA58MF147N, and PGA460_UARTHWAttrs::uartAddress.
PGA460_setThreshholds()
bool PGA460_setThreshholds (PGA460_Handle handle, PGA460_threshold threshold, const PGA460_THRBW * thrbw, PGA460_broadcast broadcastEnable)
Function to set threshold levels for PGA460.
Function to set thresholds for PGA460. User can specify any preset value 25%, 50%, or 75% or can specify user specific value.
Precondition
PGA460_init() has to be called first
Parameters
handle A PGA460_Handle
PGA460_preset User has to specify the PGA460 preset for which the threshold has to be set.
threshold User has to specify the threshold type. Currently three types are supported. If the setting is CUSTOM then the onus is on user to provide initialized thrbw structure(only threshold levels).
thrbw A pointer to PGA460_THRBW structure. This is a optional parameter needed when the tvgain is PGA460_tvgain_custom. User can pass NULL in other cases.
broadcastEnable This can take value of PGA460_broadcast_Enable or PGA460_threshold_custom. If broadcast is enabled then the broadcast command code is used.
Returns
false if eebw structure is not null else return true.
See also
PGA460_ultrasonicSensorType
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_THRBW, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_threshold_25, PGA460_threshold_50, PGA460_threshold_75, PGA460_threshold_custom, thresholdvalues25, thresholdvalues50, thresholdvalues75, and PGA460_UARTHWAttrs::uartAddress.
PGA460_setTimeVaryingGain()
bool PGA460_setTimeVaryingGain (PGA460_Handle handle, PGA460_tvgain tvgain, const PGA460_TVGBW * tvgbw, PGA460_broadcast broadcastEnable)
Function to set time varying gain values for PGA460.
Function to set time varying gain for PGA460. User can specify any preset value 25%, 50%, or 75% or can specify user specific value.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
tvgain User has to specify the time varying gain percentage If the setting is CUSTOM then the onus is on user to provide initialized tvgbw(only gain values)structure.
eebw A pointer to PGA460_TVGBW structure. This is a optional parameter needed when the tvgain is PGA460_tvgain_custom. User can pass NULL in other cases.
broadcastEnable This can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if eebw structure is null else return true.
See also
PGA460_tvgain
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_TVGBW, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_tvgain_25, PGA460_tvgain_50, PGA460_tvgain_75, PGA460_tvgain_custom, timeVaryinGainValues25, timeVaryinGainValues50, timeVaryinGainValues75, and PGA460_UARTHWAttrs::uartAddress.
PGA460_setAFEGain()
bool PGA460_setAFEGain (PGA460_Handle handle, PGA460_afegain afegain, PGA460_broadcast broadcastEnable)
Function to set AFEGAIN for PGA460.
Function to set analog front end gain for PGA460.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
afegain User has to specify the afegain. Currently 4 presets are supported. If the setting is CUSTOM then the onus is on user to provide initialized afegain byte.
afegain A pointer to afegain byte. If NULL, it will use default values.
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if afegain pointer is null else return true.
See also
PGA460_afegain
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_afegain_32_64, PGA460_afegain_46_78, PGA460_afegain_52_84, PGA460_afegain_58_90, PGA460_commandCode_SRW, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_RW::regAddr, PGA460_RW::regData, and PGA460_UARTHWAttrs::uartAddress.
PGA460_burstAndListenCmd()
bool PGA460_burstAndListenCmd (PGA460_Handle handle, PGA460_preset preset, uint8_t numOfObjects, PGA460_broadcast broadcastEnable)
Function to start Burst and Listen command for specific preset.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
PGA460_preset User has to specify the PGA460 preset for which the Burst and Listen command has to be issued.
numOfObjects number of objects to be detected. The same number of of objects should be used even in the pull ultrasonic measurement results API. Other wise there may be failure of API.
broadcastEnable This can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if incorrect number of objects specified(max is 8) or if incorrect preset is specified.
See also
PGA460_preset
PGA460_pullUltrasonicMeasurmentResults
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_P1BL, PGA460_commandCode_P2BL, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_presets_PRESET1, PGA460_presets_PRESET2, and PGA460_UARTHWAttrs::uartAddress.
PGA460_ListenOnlyCmd()
bool PGA460_ListenOnlyCmd (PGA460_Handle handle, PGA460_preset preset, uint8_t numOfObjects, PGA460_broadcast broadcastEnable)
Function to start Burst and Listen command for specific preset.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
PGA460_preset User has to specify the PGA460 preset for which the Burst and Listen command has to be issued.
numOfObjects number of objects to be detected. The same number of of objects should be used even in the pull ultrasonic measurement results API. Other wise there may be failure of API.
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if incorrect number of objects specified(max is 8) or if incorrect preset is specified.
See also
PGA460_preset
PGA460_pullUltrasonicMeasurmentResults
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_P1LO, PGA460_commandCode_P2LO, PGA460_CommandList, PGA460_communicationInterface_UART, PGA460_presets_PRESET1, PGA460_presets_PRESET2, and PGA460_UARTHWAttrs::uartAddress.
PGA460_getMeasurements()
bool PGA460_getMeasurements (PGA460_Handle handle, PGA460_ULMResults * measurementResults, uint8_t numberOfObjects, PGA460_respErrorStatusFlags * errFlags)
Function to start Burst and Listen command for specific preset.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
numOfObjects number of objects the result has to be pulled for. This should be same or less than the noOfObjects passed when initiating the Burst and Listen or ListenOnly commands. Otherwise the behaviour will be incorrect.
measurementResults A pointer to byte array of size >= 34. After the execution of API this array will hold the measurement results. The results returned are raw values. The actual distance calculation has to be done by the application by compensating for the temperature variation and the amount spent during bursting.
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
errFlags The register read and response commands to the PGA460 return a diagnostic byte as the first byte. This uint16 contains the error information(it contains diagnostic data byte for the previous transaction and contains information related to checksum verification of received data)
Returns
false if results could not be pulled or if passed for measurement Results is NULL pointer.
See also
PGA460_burstAndListenCmd
PGA460_ListenOnlyCmd
PGA460_respErrorStatusFlags
References PGA460_Object::comInterface, PGA460_Object::comInterfaceHandle, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_communicationInterface_UART, PGA460_MAXNOOFOBJECTS, PGA460_UARTHWAttrs::uartAddress, and ULM_RESP_SIZE.
PGA460_enableEchoDataDump()
bool PGA460_enableEchoDataDump (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to set echo dump bit.
Function to set the bit which enables capturing echo data dump.After calling this function the user has to initiate a burst and listen command this will start storing the the echo data dump in PGA460 memory.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
Returns
false if failed to enable the echo data dump
Parameters
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
See also
PGA460_burstAndListenCmd
References PGA460_Object::comInterface, PGA460_Config::object, PGA460_communicationInterface_UART, PGA460_DATADUMP_ENABLE_pos, PGA460_EE_CNTRL, PGA460_writeRegister(), PGA460_RW::regAddr, and PGA460_RW::regData.
PGA460_disableEchoDataDump()
bool PGA460_disableEchoDataDump (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to clear echo dump enable bit.
Function to clear the bit which enables capturing echo data dump.This API has to be called after collecting the echo data dump. So to collect the the echo data dump user first enables the echo data dump bit, then runs a burst and listen command and after elapsing the record length interval the user disables the echo data dump enable bit by calling this API.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
Returns
false if failed to enable the echo data dump
Parameters
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
See also
PGA460_burstAndListenCmd
References PGA460_Object::comInterface, PGA460_Config::object, PGA460_communicationInterface_UART, PGA460_DATADUMP_ENABLE_pos, PGA460_EE_CNTRL, PGA460_writeRegister(), PGA460_RW::regAddr, and PGA460_RW::regData.
PGA460_getEchoDataDump()
bool PGA460_getEchoDataDump (PGA460_Handle handle, uint8_t * echoDataDump, PGA460_respErrorStatusFlags * errFlags)
Function to start Burst and Listen command for specific preset.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
echoDataDump A pointer to byte array of size >= 130 bytes. After the execution of API this array will hold the measurement results
errFlags The register read and response commands to the PGA460 return a diagnostic byte as the first byte. This uint16 contains the error information(it contains diagnostic data byte for the previous transaction and contains information related to checksum verification of received data)
Returns
false if results could not be pulled or passed pointer echoDataDump is NULL.
References PGA460_Object::comInterface, PGA460_Object::comInterfaceHandle, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_communicationInterface_UART, and PGA460_UARTHWAttrs::uartAddress.
PGA460_runDiagnostic()
bool PGA460_runDiagnostic (PGA460_Handle handle, PGA460_diagnostic diagnostic, double * diagResult, PGA460_respErrorStatusFlags * errFlags)
Function to run diagnostics on PGA460.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
diagnostic required diagnostic. Based on the required diagnostic UART commands for system diag or for temperature or noise measurement is issued to PGA460
diagResult required diagnostic result is stored in this passed pointer
errFlags The register read and response commands to the PGA460 return a diagnostic byte as the first byte. This uint16 contains the error information(it contains diagnostic data byte for the previous transaction and contains information related to checksum verification of received data)
Returns
false if diagnostics could be ran or passed pointer diagResult is NULL.
See also
PGA460_diagnostic
References PGA460_Object::comInterface, PGA460_Object::comInterfaceHandle, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_communicationInterface_UART, PGA460_diagnostic_DPT, PGA460_diagnostic_TF, SD_RESP_SIZE, TNLR_RESP_SIZE, and PGA460_UARTHWAttrs::uartAddress.
PGA460_writeRegister()
bool PGA460_writeRegister (PGA460_Handle handle, PGA460_RW * rw, PGA460_broadcast broadcastEnable)
Function to write to register on PGA460.
Precondition
PGA460_open() has to be called first.
Parameters
handle A PGA460_Handle
rw pointer to structure containing register address and register data.
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if register write was unsuccessful or passed pointer diagResult is NULL.
See also
PGA460_RW
References PGA460_Object::comInterface, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_commandCode_SRW, PGA460_CommandList, PGA460_communicationInterface_UART, and PGA460_UARTHWAttrs::uartAddress.
Referenced by PGA460_burnEEPROM(), PGA460_disableEchoDataDump(), PGA460_enableEchoDataDump(), and PGA460_setLowPowerMode().
PGA460_readRegister()
bool PGA460_readRegister (PGA460_Handle handle, uint8_t regAddr, uint8_t * regData, PGA460_respErrorStatusFlags * errFlags)
Function to read register on PGA460. (single register read)
The read of a register in PGA460 can provide a response with one or more data bytes. This function is for only reading registers with 1 response byte.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
regAddr register address to be read.
Returns
false if diagnostics could be ran or passed pointer diagResult is NULL.
Parameters
errFlags The register read and response commands to the PGA460 return a diagnostic byte as the first byte. This uint16 contains the error information(it contains diagnostic data byte for the previous transaction and contains information related to checksum verification of received data)
See also
PGA460_diagnostic
References PGA460_Object::comInterface, PGA460_Object::comInterfaceHandle, PGA460_Config::hwAttrs, PGA460_Config::object, PGA460_communicationInterface_UART, and PGA460_UARTHWAttrs::uartAddress.
Referenced by PGA460_burnEEPROM().
PGA460_burnEEPROM()
bool PGA460_burnEEPROM (PGA460_Handle handle)
Function to burn EEPROM of PGA460.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
Returns
false if EEPROM burn was not successful
References PGA460_broadcast_Disable, PGA460_EE_CNTRL, PGA460_EECTRL_EEPGST_pos, PGA460_EECTRL_EEPRG_pos, PGA460_EECTRL_EEUNLCK_pos, PGA460_EEPROM_UNLOCK, PGA460_readRegister(), PGA460_writeRegister(), PGA460_RW::regAddr, and PGA460_RW::regData.
PGA460_setLowPowerMode()
bool PGA460_setLowPowerMode (PGA460_Handle handle, PGA460_broadcast broadcastEnable)
Function to move PGA460 to low power mode.
Precondition
PGA460_open() has to be called first
Parameters
handle A PGA460_Handle
broadcastEnable this can take value of PGA460_broadcast_Enable or PGA460_broadcast_disable. If broadcast is enabled then the broadcast command code is used.
Returns
false if we were not able to set low power mode
References PGA460_DECPL_TEMP, PGA460_DECPLTEMP_LPMEN_pos, PGA460_writeRegister(), PGA460_RW::regAddr, and PGA460_RW::regData.
PGA460_Params_init()
void PGA460_Params_init (PGA460_Params * params)
Function to initialize a PGA460_Params struct to its defaults.
Parameters
params A pointer to PGA460_Params structure for initialization.
Default values are:
 comInterface      = PGA460_communicationInterface_UART;
 maxWaitTime       = 1000;
 lpmTime           = PGA460_lpmTime_500ms;
References PGA460_defaultParams.
Copyright 2017, Texas Instruments Incorporated