SAILAPIGuide: tmp006.c File Reference
tmp006.c File Reference
#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <ti/drivers/GPIO.h>
#include <ti/drivers/I2C.h>
#include <ti/sail/tmp006/tmp006.h>
#include <unistd.h>
Macros
#define WAIT_POST_RESET 5U /* Wait time in ms after reset */
#define CELSIUS_FAHREN_CONST 1.8F /* Multiplier for conversion */
#define CELSIUS_FAHREN_ADD 32U /* Celsius to Fahrenheit added factor */
#define CELSIUS_TO_KELVIN 273.15F /* Celsius to Kelvin addition factor */
#define CELSIUS_PER_LSB 0.03125F /* Degrees celsius per LSB */
#define READ_BUF_SIZE 2U
#define WRITE_BUF_SIZE 3U
#define CFG_SW_RST 0x8000U /* Software reset */
#define CFG_CONV_ON 0x7000U /* Conversion on mode */
#define CFG_DATARDY 0x0100U /* Data Ready pin enable */
#define CFG_DATARDY_STATUS 0x0080U /* Data Ready pin enable */
#define TMP006_CCONST_A1 1.75E-3
#define TMP006_CCONST_A2 -1.678E-5
#define TMP006_CCONST_TREF 298.15
#define TMP006_CCONST_B0 -2.94E-5
#define TMP006_CCONST_B1 -5.7E-7
#define TMP006_CCONST_B2 4.63E-9
#define TMP006_CCONST_C2 13.4
#define TMP006_CCONST_LSB_SIZE 156.25E-9
Functions
bool TMP006_close (TMP006_Handle handle)
Function to close a TMP006 sensor specified by the TMP006 handle.
bool TMP006_disableDataReady (TMP006_Handle handle)
Function to disable the data ready pin and GPIO interrupt.
bool TMP006_disableConversions (TMP006_Handle handle)
Function to put TMP006 sensor is low power state.
bool TMP006_enableDataReady (TMP006_Handle handle)
Function to enable the data ready pin and GPIO interrupt.
bool TMP006_enableConversions (TMP006_Handle handle)
Function to restore TMP006 to normal power operation.
bool TMP006_getDieTemp (TMP006_Handle handle, TMP006_TempScale scale, float *data)
Function to read die temperature.
bool TMP006_getObjTemp (TMP006_Handle handle, TMP006_TempScale scale, float *data)
Function to read object temperature.
bool TMP006_getDataReadyStatus (TMP006_Handle handle, TMP006_ConversionStatus *conversionStatus)
Function to get the data ready status.
void TMP006_init ()
Function to initialize TMP006 driver.
TMP006_Handle TMP006_open (unsigned int tmp006Index, I2C_Handle i2cHandle, TMP006_Params *params)
Function to open a given TMP006 sensor.
void TMP006_Params_init (TMP006_Params *params)
Function to initialize a TMP006_Params struct to its defaults.
bool TMP006_readRegister (TMP006_Handle handle, uint16_t *data, uint8_t registerAddress)
Read function for advanced users.
bool TMP006_writeRegister (TMP006_Handle handle, uint16_t data, uint8_t registerAddress)
Write function for advanced users. This is not thread safe.
Variables
const TMP006_Params TMP006_defaultParams
TMP006_Config TMP006_config []
Macro Definition Documentation
WAIT_POST_RESET
#define WAIT_POST_RESET 5U /* Wait time in ms after reset */
Referenced by TMP006_open().
CELSIUS_FAHREN_CONST
#define CELSIUS_FAHREN_CONST 1.8F /* Multiplier for conversion */
Referenced by TMP006_getDieTemp().
CELSIUS_FAHREN_ADD
#define CELSIUS_FAHREN_ADD 32U /* Celsius to Fahrenheit added factor */
Referenced by TMP006_getDieTemp().
CELSIUS_TO_KELVIN
#define CELSIUS_TO_KELVIN 273.15F /* Celsius to Kelvin addition factor */
Referenced by TMP006_getDieTemp().
CELSIUS_PER_LSB
#define CELSIUS_PER_LSB 0.03125F /* Degrees celsius per LSB */
READ_BUF_SIZE
#define READ_BUF_SIZE 2U
Referenced by TMP006_readRegister().
WRITE_BUF_SIZE
#define WRITE_BUF_SIZE 3U
Referenced by TMP006_writeRegister().
CFG_SW_RST
#define CFG_SW_RST 0x8000U /* Software reset */
Referenced by TMP006_open().
CFG_CONV_ON
#define CFG_CONV_ON 0x7000U /* Conversion on mode */
Referenced by TMP006_disableConversions(), TMP006_enableConversions(), and TMP006_open().
CFG_DATARDY
#define CFG_DATARDY 0x0100U /* Data Ready pin enable */
Referenced by TMP006_disableDataReady(), and TMP006_enableDataReady().
CFG_DATARDY_STATUS
#define CFG_DATARDY_STATUS 0x0080U /* Data Ready pin enable */
Referenced by TMP006_getDataReadyStatus().
TMP006_CCONST_A1
#define TMP006_CCONST_A1 1.75E-3
TMP006_CCONST_A2
#define TMP006_CCONST_A2 -1.678E-5
TMP006_CCONST_TREF
#define TMP006_CCONST_TREF 298.15
TMP006_CCONST_B0
#define TMP006_CCONST_B0 -2.94E-5
TMP006_CCONST_B1
#define TMP006_CCONST_B1 -5.7E-7
TMP006_CCONST_B2
#define TMP006_CCONST_B2 4.63E-9
TMP006_CCONST_C2
#define TMP006_CCONST_C2 13.4
TMP006_CCONST_LSB_SIZE
#define TMP006_CCONST_LSB_SIZE 156.25E-9
Function Documentation
TMP006_close()
bool TMP006_close (TMP006_Handle handle)
Function to close a TMP006 sensor specified by the TMP006 handle.
The TMP006 hardware will be placed in a low power state in which ADC conversions are disabled. If there is GPIO pin configured to DRDY(data ready) then GPIO pin interrupts will be disabled. The I2C handle is not affected.
Precondition
TMP006_open() had to be called first.
Parameters
handle A TMP006_Handle returned from TMP006_open()
Returns
true on success or false upon failure.
References TMP006_Object::callback, TMP006_Object::i2cHandle, TMP006_Config::object, TMP006_disableConversions(), and TMP006_disableDataReady().
TMP006_disableDataReady()
bool TMP006_disableDataReady (TMP006_Handle handle)
Function to disable the data ready pin and GPIO interrupt.
This function will disable the data ready pin on the specified TMP006 sensor.Interrupts on the TMP006 specific GPIO index will be disabled. Any temperature limits set are not affected. This function is not thread safe when used in conjunction with TMP006_enableDataReady() (ie. A thread is executing TMP006_disableDataReady() but preempted by a higher priority thread that calls TMP006_enableDataReady() on the same handle).
See also
TMP006_enableDataReady()
Precondition
TMP006_enableDataReady() had to be called first in order for this function to have an effect.
Parameters
handle A TMP006_Handle
Returns
true on success or false upon failure.
References CFG_DATARDY, TMP006_Config::hwAttrs, TMP006_Config::object, TMP006_CONFIG, TMP006_readRegister(), and TMP006_writeRegister().
Referenced by TMP006_close().
TMP006_disableConversions()
bool TMP006_disableConversions (TMP006_Handle handle)
Function to put TMP006 sensor is low power state.
This function will place the specified TMP006 sensor in a low power state. All settings are retained. Temperature and voltage readings are invalid in this state. This function is not thread safe when used in conjunction with TMP006_enableConversions().
See also
TMP006_enableConversions()
Precondition
TMP006_open() had to be called first.
Parameters
handle A TMP006_Handle
Returns
true on success or false upon failure.
References CFG_CONV_ON, TMP006_CONFIG, TMP006_readRegister(), and TMP006_writeRegister().
Referenced by TMP006_close().
TMP006_enableDataReady()
bool TMP006_enableDataReady (TMP006_Handle handle)
Function to enable the data ready pin and GPIO interrupt.
This function will enable the data ready pin on the specified TMP006 sensor. Interrupts on the TMP006 specific GPIO index will be enabled. This function is not thread safe when used in conjunction with TMP006_disableDataReady() (ie. A thread is executing TMP006_enableDataReady() but preempted by a higher priority thread that calls TMP006_disableDataReady() on the same handle).
See also
TMP006_disableDataReady()
Precondition
TMP006_open() or had to be called first.
Parameters
handle A TMP006_Handle
Returns
true on success or false upon failure.
References CFG_DATARDY, TMP006_Config::hwAttrs, TMP006_Config::object, TMP006_CONFIG, TMP006_readRegister(), and TMP006_writeRegister().
TMP006_enableConversions()
bool TMP006_enableConversions (TMP006_Handle handle)
Function to restore TMP006 to normal power operation.
This function will restore ADC conversions on the specified TMP006 sensor. Temperature and voltage readings may be invalid up to 4 seconds following this function call. This function is not thread safe when used in conjunction with TMP006_disableConversions().
See also
TMP006_disableConversions
Precondition
TMP006_disableConversions() had to be called first.
Parameters
handle A TMP006_Handle
Returns
true on success or false upon failure.
References CFG_CONV_ON, TMP006_CONFIG, TMP006_readRegister(), and TMP006_writeRegister().
TMP006_getDieTemp()
bool TMP006_getDieTemp (TMP006_Handle handle, TMP006_TempScale scale, float * temp)
Function to read die temperature.
This function will return the temperature of the die. Full scale allows a result of up to (+/-)256 (C).
Parameters
handle A TMP006_Handle
scale A TMP006_TempScale field specifying the temperature format.
temp A pointer to a float in which temperature data will be stored in.
Returns
true on success or false upon failure.
References CELSIUS_FAHREN_ADD, CELSIUS_FAHREN_CONST, CELSIUS_TO_KELVIN, TMP006_DIE_TEMP, TMP006_FAHREN, TMP006_KELVIN, and TMP006_readRegister().
TMP006_getObjTemp()
bool TMP006_getObjTemp (TMP006_Handle handle, TMP006_TempScale scale, float * temp)
Function to read object temperature.
This function will return the temperature of the object in the field of view of the specified TMP006 sensor. Full scale allows a result of up to (+/-)256 (C).
Parameters
handle A TMP006_Handle
scale A TMP006_TempScale field specifying the temperature format.
temp A pointer to a float in which temperature data will be stored in.
Returns
true on success or false upon failure.
References TMP006_DIE_TEMP, TMP006_readRegister(), and TMP006_VOBJ.
TMP006_getDataReadyStatus()
bool TMP006_getDataReadyStatus (TMP006_Handle handle, TMP006_ConversionStatus * conversionStatus)
Function to get the data ready status.
This function will get the status of conversion.
Parameters
handle A TMP006_Handle
conversionStatus a pointer to a TMP006_ConversionStatus where conversion status will be stored
Returns
true on success or false upon failure.
References CFG_DATARDY_STATUS, TMP006_CONFIG, TMP006_DataNotReady, TMP006_DataReady, and TMP006_readRegister().
TMP006_init()
void TMP006_init ()
Function to initialize TMP006 driver.
This function will initialize the TMP006 driver.
References TMP006_Config::object.
TMP006_open()
TMP006_Handle TMP006_open (unsigned int tmp006Index, I2C_Handle i2cHandle, TMP006_Params * params)
Function to open a given TMP006 sensor.
Function to initialize a given TMP006 sensor specified by the particular index value. This function must be called from a thread context. If one intends to use the data ready pin, a callBack function must be specified in the TMP006_Params structure. Additionally, a gpioIndex must be setup and specified in the TMP006_HWAttrs structure.
The I2C controller must be operating in BLOCKING mode. Failure to ensure the I2C_Handle is in BLOCKING mode will result in undefined behavior.
The user should ensure that each sensor has its own slaveAddress, gpioIndex (if alarming) and tmp006Index.
Precondition
TMP006_init() has to be called first
Parameters
tmp006Index Logical sensor number for the TMP006 indexed into the TMP006_config table
i2cHandle An I2C_Handle opened in BLOCKING mode
*params A pointer to TMP006_Params structure. If NULL, it will use default values.
Returns
A TMP006_Handle on success, or a NULL on failure.
See also
TMP006_init()
TMP006_Params_init()
TMP006_close()
References TMP006_Object::callback, TMP006_Params::callback, CFG_CONV_ON, CFG_SW_RST, TMP006_Params::conversions, TMP006_Params::dataReady, TMP006_HWAttrs::gpioIndex, TMP006_Object::i2cHandle, TMP006_Object::S0, TMP006_Params::S0, TMP006_CONFIG, TMP006_writeRegister(), and WAIT_POST_RESET.
TMP006_Params_init()
void TMP006_Params_init (TMP006_Params * params)
Function to initialize a TMP006_Params struct to its defaults.
Parameters
params A pointer to TMP006_Params structure for initialization.
Default values are: conversions = TMP006_4CONV intComp = TMP006_IntMode transientCorrect = TMP006_TCEnable callback = NULL
References TMP006_defaultParams.
TMP006_readRegister()
bool TMP006_readRegister (TMP006_Handle handle, uint16_t * data, uint8_t registerAddress)
Read function for advanced users.
Parameters
handle A TMP006_Handle
registerAddress Register address
data A pointer to a data register in which received data will be written to. Must be 16 bits.
Returns
true on success or false upon failure.
References TMP006_Config::hwAttrs, TMP006_Config::object, and READ_BUF_SIZE.
Referenced by TMP006_disableConversions(), TMP006_disableDataReady(), TMP006_enableConversions(), TMP006_enableDataReady(), TMP006_getDataReadyStatus(), TMP006_getDieTemp(), and TMP006_getObjTemp().
TMP006_writeRegister()
bool TMP006_writeRegister (TMP006_Handle handle, uint16_t data, uint8_t registerAddress)
Write function for advanced users. This is not thread safe.
When writing to a handle, it is possible to overwrite data written by another thread.
For example: Thread A and B are writing to the configuration register. Thread A has a higher priority than THread B. Thread B is running and reads the configuration register. Thread A then preempts Thread B and reads the configuration register, performs a logical OR and writes to the configuration register. Thread B then resumes execution and performs its logical OR and writes to the configuration register–overwriting the data written by Thread A.
Such instances can be prevented through the use of Semaphores. Below is an example which utilizes an initialized Semaphore_handle, tmp006Lock.
if (0 == sem_wait(&tmp006Lock))
{
    //Perform read/write operations
    sem_post(tmp006Lock);
}
else
{
    //handle error scenario
}
Parameters
handle A TMP006_Handle
data A uint16_t containing the 2 bytes to be written to the TMP006 sensor.
registerAddress Register address.
Returns
true on success or false upon failure.
References TMP006_Config::hwAttrs, TMP006_Config::object, and WRITE_BUF_SIZE.
Referenced by TMP006_disableConversions(), TMP006_disableDataReady(), TMP006_enableConversions(), TMP006_enableDataReady(), and TMP006_open().
Variable Documentation
TMP006_defaultParams
const TMP006_Params TMP006_defaultParams
Initial value:
= {
        TMP006_4CONV,
        TMP006_DataReadyDisable,
        NULL,
        6.4E-14
}
Referenced by TMP006_Params_init().
TMP006_config
TMP006_Config TMP006_config[]
Copyright 2017, Texas Instruments Incorporated